# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_plot.ui'
#
# Created: Wed Nov 16 21:42:29 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1305, 775)
        self.master_container = QtGui.QWidget(MainWindow)
        self.master_container.setObjectName(_fromUtf8("master_container"))
        self.gridLayout = QtGui.QGridLayout(self.master_container)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plot_container = QtGui.QHBoxLayout()
        self.plot_container.setObjectName(_fromUtf8("plot_container"))
        self.plot_left = PlotWidget(self.master_container)
        self.plot_left.setObjectName(_fromUtf8("plot_left"))
        self.plot_container.addWidget(self.plot_left)
        self.plot_right = PlotWidget(self.master_container)
        self.plot_right.setObjectName(_fromUtf8("plot_right"))
        self.plot_container.addWidget(self.plot_right)
        self.gridLayout.addLayout(self.plot_container, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.g0_diffAmp = QtGui.QGroupBox(self.master_container)
        self.g0_diffAmp.setObjectName(_fromUtf8("g0_diffAmp"))
        self.verticalLayout = QtGui.QVBoxLayout(self.g0_diffAmp)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.g0_diffAmp)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.fontComboBox_3 = QtGui.QFontComboBox(self.groupBox)
        self.fontComboBox_3.setObjectName(_fromUtf8("fontComboBox_3"))
        self.verticalLayout_2.addWidget(self.fontComboBox_3)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.fontComboBox_2 = QtGui.QFontComboBox(self.groupBox)
        self.fontComboBox_2.setObjectName(_fromUtf8("fontComboBox_2"))
        self.verticalLayout_2.addWidget(self.fontComboBox_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.fontComboBox = QtGui.QFontComboBox(self.groupBox)
        self.fontComboBox.setEnabled(True)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.verticalLayout_2.addWidget(self.fontComboBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.g0_diffAmp)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.fontComboBox_6 = QtGui.QFontComboBox(self.groupBox_2)
        self.fontComboBox_6.setObjectName(_fromUtf8("fontComboBox_6"))
        self.verticalLayout_3.addWidget(self.fontComboBox_6)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.fontComboBox_4 = QtGui.QFontComboBox(self.groupBox_2)
        self.fontComboBox_4.setObjectName(_fromUtf8("fontComboBox_4"))
        self.verticalLayout_3.addWidget(self.fontComboBox_4)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.fontComboBox_5 = QtGui.QFontComboBox(self.groupBox_2)
        self.fontComboBox_5.setObjectName(_fromUtf8("fontComboBox_5"))
        self.verticalLayout_3.addWidget(self.fontComboBox_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addWidget(self.g0_diffAmp)
        self.widget = QtGui.QWidget(self.master_container)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(self.groupBox_3)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.fontComboBox_7 = QtGui.QFontComboBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox_7.sizePolicy().hasHeightForWidth())
        self.fontComboBox_7.setSizePolicy(sizePolicy)
        self.fontComboBox_7.setMinimumSize(QtCore.QSize(80, 0))
        self.fontComboBox_7.setFrame(True)
        self.fontComboBox_7.setObjectName(_fromUtf8("fontComboBox_7"))
        self.verticalLayout_5.addWidget(self.fontComboBox_7)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.groupBox_3)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_8 = QtGui.QLabel(self.widget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_6.addWidget(self.label_8)
        self.fontComboBox_8 = QtGui.QFontComboBox(self.widget_3)
        self.fontComboBox_8.setObjectName(_fromUtf8("fontComboBox_8"))
        self.verticalLayout_6.addWidget(self.fontComboBox_8)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.groupBox_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_9 = QtGui.QLabel(self.widget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_7.addWidget(self.label_9)
        self.fontComboBox_9 = QtGui.QFontComboBox(self.widget_4)
        self.fontComboBox_9.setObjectName(_fromUtf8("fontComboBox_9"))
        self.verticalLayout_7.addWidget(self.fontComboBox_9)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frame = QtGui.QFrame(self.groupBox_4)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8.addWidget(self.frame)
        self.widget_5 = QtGui.QWidget(self.groupBox_4)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_9.addWidget(self.label_10)
        self.fontComboBox_10 = QtGui.QFontComboBox(self.groupBox_5)
        self.fontComboBox_10.setObjectName(_fromUtf8("fontComboBox_10"))
        self.verticalLayout_9.addWidget(self.fontComboBox_10)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_9.addWidget(self.label_11)
        self.fontComboBox_11 = QtGui.QFontComboBox(self.groupBox_5)
        self.fontComboBox_11.setObjectName(_fromUtf8("fontComboBox_11"))
        self.verticalLayout_9.addWidget(self.fontComboBox_11)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_10.addWidget(self.label_12)
        self.fontComboBox_12 = QtGui.QFontComboBox(self.groupBox_6)
        self.fontComboBox_12.setObjectName(_fromUtf8("fontComboBox_12"))
        self.verticalLayout_10.addWidget(self.fontComboBox_12)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_10.addWidget(self.label_13)
        self.fontComboBox_13 = QtGui.QFontComboBox(self.groupBox_6)
        self.fontComboBox_13.setObjectName(_fromUtf8("fontComboBox_13"))
        self.verticalLayout_10.addWidget(self.fontComboBox_13)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_11.addWidget(self.label_14)
        self.fontComboBox_14 = QtGui.QFontComboBox(self.groupBox_7)
        self.fontComboBox_14.setObjectName(_fromUtf8("fontComboBox_14"))
        self.verticalLayout_11.addWidget(self.fontComboBox_14)
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.fontComboBox_15 = QtGui.QFontComboBox(self.groupBox_7)
        self.fontComboBox_15.setObjectName(_fromUtf8("fontComboBox_15"))
        self.verticalLayout_11.addWidget(self.fontComboBox_15)
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_12.addWidget(self.label_16)
        self.fontComboBox_16 = QtGui.QFontComboBox(self.groupBox_8)
        self.fontComboBox_16.setObjectName(_fromUtf8("fontComboBox_16"))
        self.verticalLayout_12.addWidget(self.fontComboBox_16)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_12.addWidget(self.label_17)
        self.fontComboBox_17 = QtGui.QFontComboBox(self.groupBox_8)
        self.fontComboBox_17.setObjectName(_fromUtf8("fontComboBox_17"))
        self.verticalLayout_12.addWidget(self.fontComboBox_17)
        self.horizontalLayout_3.addWidget(self.groupBox_8)
        self.verticalLayout_8.addWidget(self.widget_5)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout_2.addWidget(self.widget)
        self.g2_graph = QtGui.QGroupBox(self.master_container)
        self.g2_graph.setObjectName(_fromUtf8("g2_graph"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.g2_graph)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_6 = PlotWidget(self.g2_graph)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_4.addWidget(self.widget_6)
        self.horizontalLayout_2.addWidget(self.g2_graph)
        self.g3_graphControls = QtGui.QGroupBox(self.master_container)
        self.g3_graphControls.setObjectName(_fromUtf8("g3_graphControls"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.g3_graphControls)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupBox_9 = QtGui.QGroupBox(self.g3_graphControls)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_9)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_2.addWidget(self.checkBox_4, 2, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_9)
        self.label_18 = QtGui.QLabel(self.g3_graphControls)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_13.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.g3_graphControls)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_13.addWidget(self.label_19)
        self.line = QtGui.QFrame(self.g3_graphControls)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_13.addWidget(self.line)
        self.label_20 = QtGui.QLabel(self.g3_graphControls)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_13.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.g3_graphControls)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_13.addWidget(self.label_21)
        self.line_2 = QtGui.QFrame(self.g3_graphControls)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_13.addWidget(self.line_2)
        self.label_22 = QtGui.QLabel(self.g3_graphControls)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_13.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.g3_graphControls)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_13.addWidget(self.label_23)
        self.line_3 = QtGui.QFrame(self.g3_graphControls)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_13.addWidget(self.line_3)
        self.label_24 = QtGui.QLabel(self.g3_graphControls)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_13.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.g3_graphControls)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_13.addWidget(self.label_25)
        self.line_4 = QtGui.QFrame(self.g3_graphControls)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_13.addWidget(self.line_4)
        self.widget_7 = QtGui.QWidget(self.g3_graphControls)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.widget_7)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.checkBox_5 = QtGui.QCheckBox(self.widget_7)
        self.checkBox_5.setTristate(False)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_5.addWidget(self.checkBox_5)
        self.verticalLayout_13.addWidget(self.widget_7)
        self.horizontalLayout_2.addWidget(self.g3_graphControls)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.master_container)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.g0_diffAmp.setTitle(_translate("MainWindow", "Dif. Amplifier", None))
        self.groupBox.setTitle(_translate("MainWindow", "Outputs", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "DELETE", None))
        self.label_4.setText(_translate("MainWindow", "TextLabel", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Main  Control", None))
        self.label_7.setText(_translate("MainWindow", "Control", None))
        self.label_8.setText(_translate("MainWindow", "Meas. Rate", None))
        self.label_9.setText(_translate("MainWindow", "Ref. Channel", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Osciloscope", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Ch1", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.label_11.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Ch2", None))
        self.label_12.setText(_translate("MainWindow", "TextLabel", None))
        self.label_13.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Ch3", None))
        self.label_14.setText(_translate("MainWindow", "TextLabel", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Ch4", None))
        self.label_16.setText(_translate("MainWindow", "TextLabel", None))
        self.label_17.setText(_translate("MainWindow", "TextLabel", None))
        self.g2_graph.setTitle(_translate("MainWindow", "Graph", None))
        self.g3_graphControls.setTitle(_translate("MainWindow", "Graph Controls", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Show", None))
        self.checkBox_3.setText(_translate("MainWindow", "U1", None))
        self.checkBox_2.setText(_translate("MainWindow", "U2", None))
        self.checkBox.setText(_translate("MainWindow", "U3", None))
        self.checkBox_4.setText(_translate("MainWindow", "U4", None))
        self.label_18.setText(_translate("MainWindow", "TextLabel", None))
        self.label_19.setText(_translate("MainWindow", "TextLabel", None))
        self.label_20.setText(_translate("MainWindow", "TextLabel", None))
        self.label_21.setText(_translate("MainWindow", "TextLabel", None))
        self.label_22.setText(_translate("MainWindow", "TextLabel", None))
        self.label_23.setText(_translate("MainWindow", "TextLabel", None))
        self.label_24.setText(_translate("MainWindow", "TextLabel", None))
        self.label_25.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton.setText(_translate("MainWindow", "Start", None))
        self.checkBox_5.setText(_translate("MainWindow", "Cont.", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

