# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectro_layout.ui'
#
# Created: Tue Jan 24 19:19:34 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(933, 591)
        self.master_container = QtGui.QWidget(MainWindow)
        self.master_container.setObjectName(_fromUtf8("master_container"))
        self.gridLayout = QtGui.QGridLayout(self.master_container)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plot_container = QtGui.QHBoxLayout()
        self.plot_container.setObjectName(_fromUtf8("plot_container"))
        self.plot_left = PlotWidget(self.master_container)
        self.plot_left.setObjectName(_fromUtf8("plot_left"))
        self.plot_container.addWidget(self.plot_left)
        self.plot_right = PlotWidget(self.master_container)
        self.plot_right.setObjectName(_fromUtf8("plot_right"))
        self.plot_container.addWidget(self.plot_right)
        self.gridLayout.addLayout(self.plot_container, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.g0_diffAmp = QtGui.QGroupBox(self.master_container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g0_diffAmp.sizePolicy().hasHeightForWidth())
        self.g0_diffAmp.setSizePolicy(sizePolicy)
        self.g0_diffAmp.setMinimumSize(QtCore.QSize(120, 0))
        self.g0_diffAmp.setMaximumSize(QtCore.QSize(125, 350))
        self.g0_diffAmp.setObjectName(_fromUtf8("g0_diffAmp"))
        self.verticalLayout = QtGui.QVBoxLayout(self.g0_diffAmp)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.g0_diffAmp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(123, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lab_dif_amp = QtGui.QLabel(self.groupBox)
        self.lab_dif_amp.setObjectName(_fromUtf8("lab_dif_amp"))
        self.verticalLayout_2.addWidget(self.lab_dif_amp)
        self.cbox_dif_amp = QtGui.QFontComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_dif_amp.sizePolicy().hasHeightForWidth())
        self.cbox_dif_amp.setSizePolicy(sizePolicy)
        self.cbox_dif_amp.setMinimumSize(QtCore.QSize(80, 0))
        self.cbox_dif_amp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbox_dif_amp.setObjectName(_fromUtf8("cbox_dif_amp"))
        self.verticalLayout_2.addWidget(self.cbox_dif_amp)
        self.lab_pos_amp = QtGui.QLabel(self.groupBox)
        self.lab_pos_amp.setObjectName(_fromUtf8("lab_pos_amp"))
        self.verticalLayout_2.addWidget(self.lab_pos_amp)
        self.cbox_pos_amp = QtGui.QFontComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_pos_amp.sizePolicy().hasHeightForWidth())
        self.cbox_pos_amp.setSizePolicy(sizePolicy)
        self.cbox_pos_amp.setMinimumSize(QtCore.QSize(80, 0))
        self.cbox_pos_amp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbox_pos_amp.setObjectName(_fromUtf8("cbox_pos_amp"))
        self.verticalLayout_2.addWidget(self.cbox_pos_amp)
        self.lab_neg_amp = QtGui.QLabel(self.groupBox)
        self.lab_neg_amp.setObjectName(_fromUtf8("lab_neg_amp"))
        self.verticalLayout_2.addWidget(self.lab_neg_amp)
        self.cbox_neg_amp = QtGui.QFontComboBox(self.groupBox)
        self.cbox_neg_amp.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_neg_amp.sizePolicy().hasHeightForWidth())
        self.cbox_neg_amp.setSizePolicy(sizePolicy)
        self.cbox_neg_amp.setMinimumSize(QtCore.QSize(80, 0))
        self.cbox_neg_amp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbox_neg_amp.setObjectName(_fromUtf8("cbox_neg_amp"))
        self.verticalLayout_2.addWidget(self.cbox_neg_amp)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.g0_diffAmp)
        self.groupBox_2.setMaximumSize(QtCore.QSize(123, 16777215))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setMargin(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lab_gain = QtGui.QLabel(self.groupBox_2)
        self.lab_gain.setObjectName(_fromUtf8("lab_gain"))
        self.verticalLayout_3.addWidget(self.lab_gain)
        self.cbox_gain = QtGui.QFontComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_gain.sizePolicy().hasHeightForWidth())
        self.cbox_gain.setSizePolicy(sizePolicy)
        self.cbox_gain.setMinimumSize(QtCore.QSize(80, 0))
        self.cbox_gain.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbox_gain.setObjectName(_fromUtf8("cbox_gain"))
        self.verticalLayout_3.addWidget(self.cbox_gain)
        self.lab_pos_input = QtGui.QLabel(self.groupBox_2)
        self.lab_pos_input.setObjectName(_fromUtf8("lab_pos_input"))
        self.verticalLayout_3.addWidget(self.lab_pos_input)
        self.cbox_pos_input = QtGui.QFontComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_pos_input.sizePolicy().hasHeightForWidth())
        self.cbox_pos_input.setSizePolicy(sizePolicy)
        self.cbox_pos_input.setMinimumSize(QtCore.QSize(80, 0))
        self.cbox_pos_input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbox_pos_input.setObjectName(_fromUtf8("cbox_pos_input"))
        self.verticalLayout_3.addWidget(self.cbox_pos_input)
        self.lab_neg_input = QtGui.QLabel(self.groupBox_2)
        self.lab_neg_input.setObjectName(_fromUtf8("lab_neg_input"))
        self.verticalLayout_3.addWidget(self.lab_neg_input)
        self.cbox_neg_input = QtGui.QFontComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_neg_input.sizePolicy().hasHeightForWidth())
        self.cbox_neg_input.setSizePolicy(sizePolicy)
        self.cbox_neg_input.setMinimumSize(QtCore.QSize(80, 0))
        self.cbox_neg_input.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cbox_neg_input.setObjectName(_fromUtf8("cbox_neg_input"))
        self.verticalLayout_3.addWidget(self.cbox_neg_input)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addWidget(self.g0_diffAmp)
        self.widget = QtGui.QWidget(self.master_container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(360, 350))
        self.widget.setMaximumSize(QtCore.QSize(400, 350))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.main_control = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_control.sizePolicy().hasHeightForWidth())
        self.main_control.setSizePolicy(sizePolicy)
        self.main_control.setMinimumSize(QtCore.QSize(100, 0))
        self.main_control.setMaximumSize(QtCore.QSize(999, 100))
        self.main_control.setObjectName(_fromUtf8("main_control"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.main_control)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(self.main_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setMargin(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lab_control = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_control.sizePolicy().hasHeightForWidth())
        self.lab_control.setSizePolicy(sizePolicy)
        self.lab_control.setMinimumSize(QtCore.QSize(80, 0))
        self.lab_control.setObjectName(_fromUtf8("lab_control"))
        self.verticalLayout_5.addWidget(self.lab_control)
        self.cbox_control = QtGui.QFontComboBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_control.sizePolicy().hasHeightForWidth())
        self.cbox_control.setSizePolicy(sizePolicy)
        self.cbox_control.setMinimumSize(QtCore.QSize(20, 0))
        self.cbox_control.setFrame(True)
        self.cbox_control.setObjectName(_fromUtf8("cbox_control"))
        self.verticalLayout_5.addWidget(self.cbox_control)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.main_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lab_meas_rate = QtGui.QLabel(self.widget_3)
        self.lab_meas_rate.setObjectName(_fromUtf8("lab_meas_rate"))
        self.verticalLayout_6.addWidget(self.lab_meas_rate)
        self.cbox_measrate = QtGui.QFontComboBox(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_measrate.sizePolicy().hasHeightForWidth())
        self.cbox_measrate.setSizePolicy(sizePolicy)
        self.cbox_measrate.setObjectName(_fromUtf8("cbox_measrate"))
        self.verticalLayout_6.addWidget(self.cbox_measrate)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.main_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setMargin(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_9 = QtGui.QLabel(self.widget_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_7.addWidget(self.label_9)
        self.cbox_ref_channel = QtGui.QFontComboBox(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_ref_channel.sizePolicy().hasHeightForWidth())
        self.cbox_ref_channel.setSizePolicy(sizePolicy)
        self.cbox_ref_channel.setObjectName(_fromUtf8("cbox_ref_channel"))
        self.verticalLayout_7.addWidget(self.cbox_ref_channel)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout_4.addWidget(self.main_control)
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(999, 200))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setMargin(2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widget_5 = QtGui.QWidget(self.groupBox_4)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 155))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setMargin(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setMargin(2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_9.addWidget(self.label_10)
        self.cbox_c1_range = QtGui.QFontComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c1_range.sizePolicy().hasHeightForWidth())
        self.cbox_c1_range.setSizePolicy(sizePolicy)
        self.cbox_c1_range.setMinimumSize(QtCore.QSize(0, 0))
        self.cbox_c1_range.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbox_c1_range.setObjectName(_fromUtf8("cbox_c1_range"))
        self.verticalLayout_9.addWidget(self.cbox_c1_range)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_9.addWidget(self.label_11)
        self.cbox_c2_coupling = QtGui.QFontComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c2_coupling.sizePolicy().hasHeightForWidth())
        self.cbox_c2_coupling.setSizePolicy(sizePolicy)
        self.cbox_c2_coupling.setObjectName(_fromUtf8("cbox_c2_coupling"))
        self.verticalLayout_9.addWidget(self.cbox_c2_coupling)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setMargin(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_10.addWidget(self.label_12)
        self.cbox_c2_range = QtGui.QFontComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c2_range.sizePolicy().hasHeightForWidth())
        self.cbox_c2_range.setSizePolicy(sizePolicy)
        self.cbox_c2_range.setObjectName(_fromUtf8("cbox_c2_range"))
        self.verticalLayout_10.addWidget(self.cbox_c2_range)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_10.addWidget(self.label_13)
        self.cbox_c2_coupling_2 = QtGui.QFontComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c2_coupling_2.sizePolicy().hasHeightForWidth())
        self.cbox_c2_coupling_2.setSizePolicy(sizePolicy)
        self.cbox_c2_coupling_2.setObjectName(_fromUtf8("cbox_c2_coupling_2"))
        self.verticalLayout_10.addWidget(self.cbox_c2_coupling_2)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setMargin(2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_11.addWidget(self.label_14)
        self.cbox_c3_range = QtGui.QFontComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c3_range.sizePolicy().hasHeightForWidth())
        self.cbox_c3_range.setSizePolicy(sizePolicy)
        self.cbox_c3_range.setObjectName(_fromUtf8("cbox_c3_range"))
        self.verticalLayout_11.addWidget(self.cbox_c3_range)
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.cbox_c3_coupling = QtGui.QFontComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c3_coupling.sizePolicy().hasHeightForWidth())
        self.cbox_c3_coupling.setSizePolicy(sizePolicy)
        self.cbox_c3_coupling.setObjectName(_fromUtf8("cbox_c3_coupling"))
        self.verticalLayout_11.addWidget(self.cbox_c3_coupling)
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.widget_5)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setMargin(2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_12.addWidget(self.label_16)
        self.cbox_c4_range = QtGui.QFontComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c4_range.sizePolicy().hasHeightForWidth())
        self.cbox_c4_range.setSizePolicy(sizePolicy)
        self.cbox_c4_range.setObjectName(_fromUtf8("cbox_c4_range"))
        self.verticalLayout_12.addWidget(self.cbox_c4_range)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_12.addWidget(self.label_17)
        self.cbox_c4_coupling = QtGui.QFontComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_c4_coupling.sizePolicy().hasHeightForWidth())
        self.cbox_c4_coupling.setSizePolicy(sizePolicy)
        self.cbox_c4_coupling.setObjectName(_fromUtf8("cbox_c4_coupling"))
        self.verticalLayout_12.addWidget(self.cbox_c4_coupling)
        self.horizontalLayout_3.addWidget(self.groupBox_8)
        self.verticalLayout_8.addWidget(self.widget_5)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout_2.addWidget(self.widget)
        self.g2_graph = QtGui.QGroupBox(self.master_container)
        self.g2_graph.setMaximumSize(QtCore.QSize(300, 350))
        self.g2_graph.setObjectName(_fromUtf8("g2_graph"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.g2_graph)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_6 = PlotWidget(self.g2_graph)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_4.addWidget(self.widget_6)
        self.horizontalLayout_2.addWidget(self.g2_graph)
        self.g3_graphControls = QtGui.QGroupBox(self.master_container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g3_graphControls.sizePolicy().hasHeightForWidth())
        self.g3_graphControls.setSizePolicy(sizePolicy)
        self.g3_graphControls.setMaximumSize(QtCore.QSize(160, 350))
        self.g3_graphControls.setObjectName(_fromUtf8("g3_graphControls"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.g3_graphControls)
        self.verticalLayout_13.setSpacing(4)
        self.verticalLayout_13.setMargin(2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupBox_9 = QtGui.QGroupBox(self.g3_graphControls)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tbox_u1 = QtGui.QCheckBox(self.groupBox_9)
        self.tbox_u1.setObjectName(_fromUtf8("tbox_u1"))
        self.gridLayout_2.addWidget(self.tbox_u1, 1, 0, 1, 1)
        self.tbox_u2 = QtGui.QCheckBox(self.groupBox_9)
        self.tbox_u2.setObjectName(_fromUtf8("tbox_u2"))
        self.gridLayout_2.addWidget(self.tbox_u2, 1, 1, 1, 1)
        self.tbox_u3 = QtGui.QCheckBox(self.groupBox_9)
        self.tbox_u3.setObjectName(_fromUtf8("tbox_u3"))
        self.gridLayout_2.addWidget(self.tbox_u3, 2, 0, 1, 1)
        self.tbox_u4 = QtGui.QCheckBox(self.groupBox_9)
        self.tbox_u4.setObjectName(_fromUtf8("tbox_u4"))
        self.gridLayout_2.addWidget(self.tbox_u4, 2, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_9)
        self.lab_fi1 = QtGui.QLabel(self.g3_graphControls)
        self.lab_fi1.setObjectName(_fromUtf8("lab_fi1"))
        self.verticalLayout_13.addWidget(self.lab_fi1)
        self.lab_m1 = QtGui.QLabel(self.g3_graphControls)
        self.lab_m1.setObjectName(_fromUtf8("lab_m1"))
        self.verticalLayout_13.addWidget(self.lab_m1)
        self.line = QtGui.QFrame(self.g3_graphControls)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_13.addWidget(self.line)
        self.lab_fi2 = QtGui.QLabel(self.g3_graphControls)
        self.lab_fi2.setObjectName(_fromUtf8("lab_fi2"))
        self.verticalLayout_13.addWidget(self.lab_fi2)
        self.lab_m2 = QtGui.QLabel(self.g3_graphControls)
        self.lab_m2.setObjectName(_fromUtf8("lab_m2"))
        self.verticalLayout_13.addWidget(self.lab_m2)
        self.line_2 = QtGui.QFrame(self.g3_graphControls)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_13.addWidget(self.line_2)
        self.lab_fi3 = QtGui.QLabel(self.g3_graphControls)
        self.lab_fi3.setObjectName(_fromUtf8("lab_fi3"))
        self.verticalLayout_13.addWidget(self.lab_fi3)
        self.lab_m3 = QtGui.QLabel(self.g3_graphControls)
        self.lab_m3.setObjectName(_fromUtf8("lab_m3"))
        self.verticalLayout_13.addWidget(self.lab_m3)
        self.line_3 = QtGui.QFrame(self.g3_graphControls)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_13.addWidget(self.line_3)
        self.lab_fi4 = QtGui.QLabel(self.g3_graphControls)
        self.lab_fi4.setObjectName(_fromUtf8("lab_fi4"))
        self.verticalLayout_13.addWidget(self.lab_fi4)
        self.lab_m4 = QtGui.QLabel(self.g3_graphControls)
        self.lab_m4.setObjectName(_fromUtf8("lab_m4"))
        self.verticalLayout_13.addWidget(self.lab_m4)
        self.line_4 = QtGui.QFrame(self.g3_graphControls)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_13.addWidget(self.line_4)
        self.widget_7 = QtGui.QWidget(self.g3_graphControls)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setMargin(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.but_start = QtGui.QPushButton(self.widget_7)
        self.but_start.setObjectName(_fromUtf8("but_start"))
        self.horizontalLayout_5.addWidget(self.but_start)
        self.tbox_cont = QtGui.QCheckBox(self.widget_7)
        self.tbox_cont.setTristate(False)
        self.tbox_cont.setObjectName(_fromUtf8("tbox_cont"))
        self.horizontalLayout_5.addWidget(self.tbox_cont)
        self.verticalLayout_13.addWidget(self.widget_7)
        self.horizontalLayout_2.addWidget(self.g3_graphControls)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.master_container)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.g0_diffAmp.setTitle(_translate("MainWindow", "Dif. Amplifier", None))
        self.groupBox.setTitle(_translate("MainWindow", "Outputs", None))
        self.lab_dif_amp.setText(_translate("MainWindow", "Dif. Amp.", None))
        self.lab_pos_amp.setText(_translate("MainWindow", "Pos. Amp.", None))
        self.lab_neg_amp.setText(_translate("MainWindow", "Neg. Amp.", None))
        self.lab_gain.setText(_translate("MainWindow", "Gain", None))
        self.lab_pos_input.setText(_translate("MainWindow", "Pos. Input", None))
        self.lab_neg_input.setText(_translate("MainWindow", "Neg. Input", None))
        self.main_control.setTitle(_translate("MainWindow", "Main  Control", None))
        self.lab_control.setText(_translate("MainWindow", "Control", None))
        self.lab_meas_rate.setText(_translate("MainWindow", "Meas. Rate", None))
        self.label_9.setText(_translate("MainWindow", "Ref. Channel", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Osciloscope", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Ch1", None))
        self.label_10.setText(_translate("MainWindow", "Range", None))
        self.label_11.setText(_translate("MainWindow", "Coupling", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Ch2", None))
        self.label_12.setText(_translate("MainWindow", "Range", None))
        self.label_13.setText(_translate("MainWindow", "Coupling", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Ch3", None))
        self.label_14.setText(_translate("MainWindow", "Range", None))
        self.label_15.setText(_translate("MainWindow", "Coupling", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Ch4", None))
        self.label_16.setText(_translate("MainWindow", "Range", None))
        self.label_17.setText(_translate("MainWindow", "Coupling", None))
        self.g2_graph.setTitle(_translate("MainWindow", "Graph", None))
        self.g3_graphControls.setTitle(_translate("MainWindow", "Graph Controls", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Show", None))
        self.tbox_u1.setText(_translate("MainWindow", "U1", None))
        self.tbox_u2.setText(_translate("MainWindow", "U2", None))
        self.tbox_u3.setText(_translate("MainWindow", "U3", None))
        self.tbox_u4.setText(_translate("MainWindow", "U4", None))
        self.lab_fi1.setText(_translate("MainWindow", "Fi1 = ", None))
        self.lab_m1.setText(_translate("MainWindow", "M1 =", None))
        self.lab_fi2.setText(_translate("MainWindow", "Fi2 =", None))
        self.lab_m2.setText(_translate("MainWindow", "M2 = ", None))
        self.lab_fi3.setText(_translate("MainWindow", "Fi3 = ", None))
        self.lab_m3.setText(_translate("MainWindow", "M3 = ", None))
        self.lab_fi4.setText(_translate("MainWindow", "Fi4 = ", None))
        self.lab_m4.setText(_translate("MainWindow", "M4 = ", None))
        self.but_start.setText(_translate("MainWindow", "Start", None))
        self.tbox_cont.setText(_translate("MainWindow", "Cont.", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

