
function zinute_iu=VRM_I(ge, scp, iu, zinute_dif)
%---------------------------------------------------------
%%%AUTORIUS  ALGIMANTAS KEZIONIS %%%%%%%%%%%%
%--------------------------------------------------------
disp('IU Converter driver...');
zinute_iu=@komanda_iu;
Rmat(1,:)=[250 1e3 4e3 1.6e4 64e3 250e3 1e6 4e6 16e6 64e6 240e6];%matavimo varzos suapvaintos realios
Rmat(2,:)=[250 1e3 4e3 1.6e4 64e3 250e3 1e6 4e6 16e6 64e6 240e6];%matavimo varzos tikslios kompleksines
Rmats(1:11,1:8)=['250  om '; '1,00 kom'; '4,00 kom'; '16,0 kom'; '64,0 kom'; '256  kom'; '1,00 Mom'; '4,00 Mom'; '16,0 Mom'; '64,0 Mom'; '256  Mom'];
Rmat(3,:)=[2.2e6 2.2e6 2.2e6 2.2e6 .512e6 .128e6 32e3 8e3 2e3 500 125];%matavimo varzu ribiniai dazniai
Rmat(3,5:11)=Rmat(3,5:11)*2;
filnum(1,:)=[3.5 100 3e3 4e4];
filnum(2,:)=[250 8e3 1.3e5 2.2e6];
%%%------------------------------------------------------------------------
%%%Pagrindinis prietaisu valdymo ir b�senos nuskaitymo skydas
%%%------------------------------------------------------------------------
IUskydas1=figure(20);
set(IUskydas1,'visible','off',...
    'position',[50 100 1020 660],...
    'name','KAIMAN_4e IU Converter driver, ver.1.0 beta)',...
    'resize','on');
set(IUskydas1,'menubar','none');  %isjungtas standartinis meniu
set(IUskydas1,'toolbar','figure');    %ijungta standartine irankiu juosta
bckgr=get(0,'defaultUicontrolBackgroundColor'); %esamos OS atspalvis
set(IUskydas1,'color',bckgr); %priskiriamas esamos OS atspalvis
set(IUskydas1,'CloseRequestFcn',@my_closereqIU)
%%%------------------------------------------------------------------------
%%% skydelis.
%%%------------------------------------------------------------------------
valdymas=uipanel(IUskydas1,...
    'units','normalized',...
    'position',[.01 0.0125 0.346 0.49],...
    'BorderWidth',2,...
    'FontSize',9,...
    'title','I-U converter');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
 varzas=uibuttongroup(valdymas,...
    'units','pixels',...
    'position',[5 5 106 300],...
    'title','Rmeas',...
    'SelectionChangeFcn',@keistivarza);
varza(1:11)=0;
for ii=1:11
varza(ii)=uicontrol(varzas,'style','radio',...
    'position',[10 285-ii*23 90 20],...
    'enable','on',...
    'string',Rmats(ii,1:8));
end
I_auto = uicontrol(varzas, ...
    'style', 'checkbox', ...
    'position', [12 10 20 20], ...
    'backgroundcolor','white',...
    'value',0,...
    'enable', 'on', ...
    'callback', @set_I_auto);
uicontrol(varzas,'style','text',...
    'position',[30 10 32 20],...
    'string','Auto',...
    'FontSize',8,...
    'enable','on'); 
%-----------------------------------
kals=uibuttongroup(valdymas,...
    'units','pixels',...
    'position',[231 155 106 150],...
    'title','State',...
    'SelectionChangeFcn',@kalmat);
kal(1)=uicontrol(kals,'style','radio',...
    'position',[20 45 80 20],...
    'enable','on',...
    'string','Callibr.');
kal(2)=uicontrol(kals,'style','radio',...
    'position',[20 25 80 20],...
    'enable','on',...
    'string','Meas.');
kalmattrauto=uicontrol(kals,'style','checkbox',...
    'position',[20 5 15 15],...
    'backgroundcolor','white',...
    'value',0,...
    'enable','on',...
    'callback',@kalmat);
uicontrol(kals,'style','text',...
    'position',[40 2 32 20],...
    'string','Auto',...
     'FontSize',8,...
    'enable','on'); 
hf_lf=uicontrol(kals,'style','popupmenu',...
    'position',[20 100 65 20],...
    'string',{'LF','HF'},...
    'value',1,...
    'backgroundcolor','w',...
    'enable','off',...
    'callback',@converter);
uicontrol(kals,'style','text',...
    'position',[20 125 65 12],...
    'string','Converter',...
     'FontSize',10,...
    'enable','on'); 
%------------------------------
Ustip=uibuttongroup(valdymas,...
    'units','pixels',...
    'position',[119 5 106 145],...
    'title','U to sample',...
    'SelectionChangeFcn',@stipu);
UK(2)=uicontrol(Ustip,'style','radio',...
    'position',[20 95 60 20],...
    'enable','on',...
    'string','K=1');
UK(1)=uicontrol(Ustip,'style','radio',...
    'position',[20 30 60 20],...
    'enable','on',...
    'string','K=1/4');
%-------------------------------------
Istip=uibuttongroup(valdymas,...
    'units','pixels',...
    'position',[119 155 106 150],...
    'title','I amplifier',...
    'SelectionChangeFcn',@stipi);
IK(2)=uicontrol(Istip,'style','radio',...
    'position',[20 95 60 20],...
    'enable','on',...
    'string','KI=1');
IK(1)=uicontrol(Istip,'style','radio',...
    'position',[20 30 60 20],...
    'enable','on',...
    'string','KI=4');
%---------------------------------------
filsad=uibuttongroup(valdymas,...
    'units','pixels',...
    'position',[231 5 106 145],...
    'title','Reject at',...
    'SelectionChangeFcn',@keistifiltra);
filszd=uibuttongroup(valdymas,...
    'units','pixels',...
    'position',[231 5 106 145],...
    'title','Reject at',...
    'SelectionChangeFcn',@keistifiltra);
filad(1)=uicontrol(filsad,'style','radio',...
    'position',[20 35 80 20],...
    'enable','on',...
    'visible', 'on',...
    'string',' 250 Hz');
filad(2)=uicontrol(filsad,'style','radio',...
    'position',[20 60 80 20],...
    'enable','on',...
    'visible', 'on',...
    'string',' 8,0  kHz');
filad(3)=uicontrol(filsad,'style','radio',...
    'position',[20 85 80 20],...
    'enable','on',...
    'visible', 'on',...
    'string',' 130 kHz');
filad(4)=uicontrol(filsad,'style','radio',...
    'position',[20 110 80 20],...
    'enable','on',...
    'visible', 'on',...
    'string',' 2,0 MHz');
filzd(1)=uicontrol(filszd,'style','radio',...
    'position',[20 35 80 20],...
    'enable','on',...
    'visible', 'off',...
    'string',' 3,5 Hz');
filzd(2)=uicontrol(filszd,'style','radio',...
    'position',[20 60 80 20],...
    'enable','on',...
    'visible', 'off',...
    'string',' 100 Hz');
filzd(3)=uicontrol(filszd,'style','radio',...
    'position',[20 85 80 20],...
    'enable','on',...
    'visible', 'off',...
    'string',' 3,0 kHz');
filzd(4)=uicontrol(filszd,'style','radio',...
    'position',[20 110 80 20],...
    'enable','on',...
    'visible', 'off',...
    'string',' 40  kHz');
fcont=uicontrol(filsad,'style','checkbox',...
    'position',[20 10 19 15],...
    'backgroundcolor','white',...
    'value',0,...
    'enable','on',...
    'callback',@fcontrol);
uicontrol(filsad,'style','text',...
    'position',[35 7 32 20],...
    'string','Auto',...
     'FontSize',8,...
    'enable','on');   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
out_control = uibuttongroup(IUskydas1, ...
    'units', 'normalized', ...
    'BorderWidth',2,...
    'position', [.36 .0125 .115 .49], ...
    'FontSize',9,...2
    'title', 'Main control');
uicontrol(out_control,'style','text',...
    'position',[20 205 65 20],...
    'string','Control',...
    'enable','on');   
intext=uicontrol(out_control,'style','popupmenu',...
    'position',[20 190 65 20],...
    'string',{'GUI','Appl.'},...
    'value',1,...
    'backgroundcolor','w',...
    'enable','on',...
    'callback',@vald);
uicontrol(out_control,'style','text',...
    'position',[20 135 65 40],...
    'string','U sample max',...
    'enable','on');   
maxu=uicontrol(out_control,'style','popupmenu',...
    'position',[20 120 65 20],...
    'string',{'0.4 V','0.1 V', '25 mV'},...
    'value',2,...
    'backgroundcolor','w',...
    'enable','on',...
    'callback',@bandu);
uicontrol(out_control,'style','text',...
    'position',[20 65 65 40],...
    'string','Meas. rate',...
    'enable','on');   
rate=uicontrol(out_control,'style','popupmenu',...
    'position',[20 60 65 20],...
    'string',{'Fast','Normal','Slow'},...
    'value',2,...
    'backgroundcolor','w',...
    'enable','on',...
    'callback',@oscauto);
%%%%%%%%%%%%%%%%OSCILOSCOP%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
osc=uipanel(IUskydas1,...
    'units','normalized',...
    'position',[.482 10/800 .211 0.49],...
    'BorderWidth',2,...
    'FontSize',9,...
    'title','Osciloscop');
Chen1=uibuttongroup(osc,...
    'units','pixels',...
    'position',[5 5 94 120],...
    'title','Ch1 (I)');
uicontrol(Chen1,'style','text',...
    'position',[12 80 65 20],...
    'string','Umax',...
    'enable','on');   
ch1skale=uicontrol(Chen1,'style','popupmenu',...
    'position',[12 65 65 20],...
    'string',{num2str(scp.Channels(1).Ranges,2)},...
    'value',2,...
    'enable','on',...
    'callback',@ch1sk);
uicontrol(Chen1,'style','text',... 
    'position',[12 35 65 20],...
    'string','AC/ DC',...
    'enable','on');   
ch1jung=uicontrol(Chen1,'style','popupmenu',...
    'position',[12 20 65 20],...
    'string',{'DCV','ACV'},...
    'value',1,...
    'enable','on',...
    'callback',@ch1acdc);
Chen2=uibuttongroup(osc,...
    'units','pixels',...
    'position',[106 5 94 120],...
    'title','Ch2 (U)');
uicontrol(Chen2,'style','text',...
    'position',[12 80 65 20],...
    'string','Umax',...
    'enable','on');   
ch2skale=uicontrol(Chen2,'style','popupmenu',...
    'position',[12 65 65 20],...
    'string',{num2str(scp.Channels(2).Ranges,2)},...
    'value',2,...
    'enable','on',...
    'callback',@ch2sk);
uicontrol(Chen2,'style','text',...
    'position',[12 35 65 20],...
    'string','AC/ DC',...
    'enable','on');   
ch2jung=uicontrol(Chen2,'style','popupmenu',...
    'position',[12 20 65 20],...
    'string',{'DCV','ACV'},...
    'value',1,...
    'enable','on',...
    'callback',@ch2acdc);
kitas=uibuttongroup(osc,...
    'units','pixels',...
    'position',[5 125 194 173],...
     'title','');
uicontrol(kitas,'style','text',...
    'position',[10 35 70 20],...
    'string','Resolution',...
    'enable','on');   
resol=uicontrol(kitas,'style','popupmenu',...
    'position',[10 20 65 20],...
    'string',{'16 bit','14 bit','12 bit','8  bit'},...
    'value',1,...
    'enable','on',...
    'callback',@res); 
uicontrol(kitas,'style','text',...
    'position',[103 35 65 20],...
    'string','Trigger',...
    'enable','on');   
trig=uicontrol(kitas,'style','popupmenu',...
    'position',[100 20 80 20],...
    'string',{'Ch1','Ch2','Ext1','Ext2','Ext3', 'GenStart','GenStop','GenNewper'},...
    'value',1,...
    'backgroundcolor','w',...
    'enable','on',...
    'callback',@trigger); 
uicontrol(kitas,'style','text',...
    'position',[10 80 65 20],...
    'string','f sampl.',...
    'enable','on');   
editsf=uicontrol(kitas,'style','edit',...
    'position',[10 65 65 20],...
    'backgroundcolor','white',...
    'enable','on',...
    'string','100000',...
    'callback',@sf);  
uicontrol(kitas,'style','text',...
    'position',[103 80 65 20],...
    'string','n sampl.',...
    'enable','on');   
editns=uicontrol(kitas,'style','edit',...
    'position',[100 65 80 20],...
    'backgroundcolor','white',...
    'enable','on',...
    'string','16000',...
    'callback',@ns);  
uicontrol(kitas,'style','text',...
    'position',[25 150 140 20],...
    'string','Comand:',...
    'enable','on');   
editkom=uicontrol(kitas,'style','edit',...
    'position',[15 135 160 20],...
    'backgroundcolor','white',...
    'enable','on',...
    'string','',...
     'FontSize',7,...
    'callback',@comand);
fnrcont=uicontrol(kitas,'style','checkbox',...
    'position',[20 110 15 15],...
    'backgroundcolor','white',...
    'value',0,...
    'enable','on',...
    'callback',@oscauto);
uicontrol(kitas,'style','text',...
    'position',[35 107 100 20],...
    'string','Auto fsa, nsa, Res',...
     'FontSize',8,...
    'enable','on');   
%%%%%%%%%%%%%%%%%%GENERATOR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
gen=uipanel(IUskydas1,...
    'units','normalized',...
    'position',[.699 10/800 0.146 0.49],...
    'BorderWidth',2,...
    'FontSize',9,...
    'title','Generator');
uicontrol(gen,'style','text',...
    'position',[10 95 50 20],...
    'string','Output',...
    'enable','on');  
gpoponoff=uicontrol(gen,'style','popupmenu',...
    'position',[10 80 50 20],...
    'backgroundcolor','white',...
    'string',{'OFF','ON'},...
    'value',1,...
    'enable','on',...
    'callback',@goutput);
uicontrol(gen,'style','text',...
    'position',[70 95 65 20],...
    'string','Symmetry',...
    'enable','on');  
groutedit=uicontrol(gen,'style','edit',...
    'position',[80 80 50 20],...
    'backgroundcolor','white',...
    'string','0.5',...
    'enable','on',...
    'callback',@gsym);
ch2au=uicontrol(gen,'style','checkbox',...
    'position',[10 50 15 15],...
    'backgroundcolor','white',...
    'value',0,...
    'enable','on',...
    'callback',@ch2auto);
uicontrol(gen,'style','text',...
    'position',[25 47 100 20],...
    'string','Link with CH2',...
    'enable','on');  
uicontrol(gen,'style','text',...
    'position',[45 245 65 20],...
    'string','Form',...
    'enable','on');  
gpopform=uicontrol(gen,'style','popupmenu',...
    'position',[45 245 65 20],...
    'backgroundcolor','white',...
    'string',{'SIN', 'TRI', 'SQUA', 'DC', 'NOISE', 'ARBI'},...
    'value',1,...
    'enable','on',...
    'callback',@gsignalform); 
uicontrol(gen,'style','text',...
    'position',[45 180 65 20],...
    'string','Ampl., V',...
    'enable','on');  
gedita=uicontrol(gen,'style','edit',...
    'position',[45 165 65 20],...
    'backgroundcolor','white',...
    'enable','on',...
    'string','0.1',...
    'callback',@gsignalvolt); 
uicontrol(gen,'style','text',...
    'position',[45 215 65 20],...
    'string','Freq., Hz',...
    'enable','on');  
geditf=uicontrol(gen,'style','edit',...
    'position',[45 200 65 20],...
    'backgroundcolor','white',...
    'enable','on',...
    'string','1000',...
    'callback',@gsignalfreq); 
uicontrol(gen,'style','text',...
    'position',[45 140 65 20],...
    'string','Udc, V',...
    'enable','on');  
geditdc=uicontrol(gen,'style','edit',...
    'position',[45 125 65 20],...
    'backgroundcolor','white',...
    'enable','on',...
    'string','0',...
    'callback',@gsignaldc); 

%%%%%%%%%%%%%%%Grafika%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ograf=uipanel(IUskydas1,...
    'units','normalized',...
    'position',[.849 0.2 0.146 0.3],...
    'FontSize',9,...
    'BorderWidth',2,...
    'title','Graph');
klavisas=uicontrol(ograf,'style','pushbutton',...
    'units','pixels',...
    'position',[10 10 60 30],...
    'string','Start',...
    'callback',@pirm);
continuous=uicontrol(ograf,'style','checkbox',...
    'position',[100 10 15 15],...
    'backgroundcolor','white',...
    'value',0,...
    'enable','on');
uicontrol(ograf,'style','text',...
    'position',[75 30 55 10],...
    'string','Continuous',...
     'FontSize',8,...
    'enable','on');   
txm=uicontrol(ograf,'style','text',...
    'position',[5 40 100 20],...
    'string','M=',...
    'FontSize',8,...
    'enable','on');
txfi=uicontrol(ograf,'style','text',...
    'position',[5 65 100 20],...
    'string','FI=',...
    'FontSize',8,...
    'enable','on');
kanalas1=uicontrol(ograf,'style','checkbox',...
    'position',[5 100 15 15],...
    'backgroundcolor','b',...
    'value',1,...
    'enable','on',...
    'callback',@matytigraf);
kanalas2=uicontrol(ograf,'style','checkbox',...
    'position',[95 100 15 15],...
    'backgroundcolor','c',...
    'value',1,...
    'enable','on',...
    'callback',@matytigraf);
uicontrol(ograf,'style','text',...
    'position',[35 97 40 20],...
    'string','View',...
    'FontSize',8,...
    'enable','on');
SN=uicontrol(ograf,'style','text',...
    'position',[5 125 100 20],...
    'string','S/N=',...
    'FontSize',8,...
    'enable','on');
N=uicontrol(ograf,'style','text',...
    'position',[5 150 100 20],...
    'string','N=',...
    'FontSize',8,...
    'enable','on');
%%%%%%%%%%%%%%%%%%%%%grafine panele%%%%%%%%%%%%%%%%%%%%%%%%%%%

graf_panel=uipanel('Parent',IUskydas1,...
    'units','normalized',...
    'BorderWidth',2,...
    'position',[0.01 0.50 0.984 0.49]);
tx1=uicontrol(graf_panel,'style','text',...
    'position',[5 5 130 20],...
    'string','U1=0 V',...
    'FontSize',10,...
    'FontWeight','bold',...
    'ForegroundColor','b',...
    'enable','on'); 
tx2=uicontrol(graf_panel,'style','text',...
    'position',[400 5 130 20],...
    'string','U2=0 V',...
    'FontSize',10,...
    'FontWeight','bold',...
    'ForegroundColor','c',...
    'enable','on'); 
sub1_axes=subplot('position',[0.07 0.15 0.4 0.8],'Parent',graf_panel,'Nextplot','replacechildren'); 
sub2_axes=subplot('position',[0.55 0.15 0.4 0.8],'Parent',graf_panel,'Nextplot','replacechildren'); 
set(sub1_axes,'fontsize',8);
set(sub2_axes,'fontsize',8);
xlabel(sub1_axes,'t,s');
ylabel(sub1_axes,'U, V');
xlabel(sub2_axes,'f, Hz')
ylabel(sub2_axes, 'dBV');
set(sub1_axes,'XGrid','on','YGrid','on');
set(sub2_axes,'XGrid','on','YGrid','on');
set(sub1_axes,'color',[0 0.5 0.9]);
set(sub2_axes,'color',[0 0.5 0.9]);
%---------------------------------------------------------------------------------
%Pradiniu busenu nustatymas
%---------------------------------------------------------------------------------
set(figure(20),'visible','on'); 
valdkintamieji={varza I_auto kal kalmattrauto UK IK filad filzd fcont maxu rate,...
    ch1skale ch1jung ch2skale ch2jung resol trig  editsf editns editkom fnrcont,...
    gpoponoff groutedit ch2au gpopform gedita geditf geditdc klavisas groutedit };
%%%%%%%%%%%%%%%%%%%%%%I-U keitiklio prad. busena%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
daliklis=10;
set(varzas,'SelectedObject',varza(3)); keistivarza;
set(filsad,'SelectedObject',filad(2)); keistifiltra;
%set(filszd,'SelectedObject',filzd(2)); keistifiltra;
fill=filnum(2,:);
set(Istip,'SelectedObject',IK(2)); stipi;
set(Ustip,'SelectedObject',UK(2)); stipu; 
set(kals,'SelectedObject',kal(1)); kalmat('nieko'); 
set(rate,'enable','on');
measrate('Fast');
%%%%%%%%%%%%%%%%%%%%% OSC pradine busena %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ch1sk;ch1acdc;ch2sk;ch2acdc;res;trigger;sf;ns;
set(ch1jung,'value',1);ch1acdc;
set(ch1skale,'value',2);ch1sk;
set(ch2jung,'value',1);ch2acdc;
set(ch2skale,'value',2);ch2sk;
set(resol,'value',1);res;
set(trig,'value',6);trigger;%kai burst mode
%set(trig,'value',2);trigger;%kai ne burst moda
set(editsf, 'string','3125000'); sf; 
set(editns,'string','16000'); ns;
%%%%%%%%%%%%%%%%%%% Gen. pradine busena %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
goutput;gsym;gsignalform;gsignalvolt;gsignalfreq;gsignaldc;
set(gpoponoff,'value',2);goutput;
set(groutedit,'string','0.5');gsym;
set(gpopform,'value',1);gsignalform;
set(gedita,'string','0.1');gsignalvolt;
nominali_itampa=.1; 
set(geditf,'string','1000');gsignalfreq;
set(geditdc,'string','0');gsignaldc;
ge.BurstMode=2;
ge.BurstCount=10;
ge.TriggerOutputs(1).Enabled=1;
ge.TriggerOutputs(1).Event=1;
%%%%%%%%%%%%%%%% KITA %%%%%%%%%%%%%%%%%%%%%%
set(fnrcont,'value',1);oscauto;
set(fcont,'value',1);fcontrol;
nepiesti=false;
tvarka=false;
hspek=0;
hform=0;
help;
disp('OK');
%Busenos=struct('Genvoltage',1,'AttenuatorU',.25,'GainI',1,'ResistorNo',3,'Ch2scale',.2);
%%%------------------------------------------------------------------------        
%%%Pagrindinio skydo elementu iskvietimo funkciju programavimas (callback)
%%%------------------------------------------------------------------------
 %%%%%%%%%%%%%%% I_U keitiklio funkcijos %%%%%%%%%%%%%%%
function fcontrol(~,~)%ijunfgti/isjungti automatini filtro valdyma ir nustatyi
    %reikalinga filtra
    f=ge.Frequency;
    b=iu.range;
    a=get(fcont,'value');
    switch b
        case 'LF'
            fill=filnum(1,:);
            set(filzd,'visible','on');
            set(filad,'visible','off');
            aa=find(filzd==get(filszd,'SelectedObject'));
        case 'HF'
            fill=filnum(2,:);
            set(filad,'visible','on');
            set(filzd,'visible','off');
            aa=find(filad==get(filsad,'SelectedObject'));
    end
    kk=find(fill>f,1);
    if a==1
        set(filad,'enable','off');
        set(filzd,'enable','off');
        if aa~=kk;% jei dar neijungtas reikalingas filtras
            iu.filter=kk;
            set(filsad,'SelectedObject',filad(kk));
            set(filszd,'SelectedObject',filzd(kk));
        end
    else
        set(filad,'enable','on');
        set(filzd,'enable','on');
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function keistivarza(~,~)
    %ijungti reikalinga matavimo varza
    a=find(varza==get(varzas,'SelectedObject'));
    if ge.Frequency>Rmat(3,a)%cia automatiskai pastatoma varza, jei esamai varzai daznis per didelis
        kjk=find(ge.Frequency<=Rmat(3,:),1,'last');
        if a>kjk;
            a=kjk;
        end
    end
    iu.resistor=a; %ijungiam reikalinga varza
    set(varza(a),'value',1);%pazymim ijungta varza GUI
    a=iu.range;%kuris keitiklis 
    switch a
        case 'LF'
            set(hf_lf,'value',1);
        case 'HF'
            set(hf_lf,'value',2);
    end
    fcontrol;pause(.05);
end
function set_I_auto(~,~) %autometinio varzos radimo varnele
    if get(I_auto,'value')==1
        set(varza,'enable','off');
        set(gedita,'enable','off');
        set(IK,'enable','off');
        set(UK,'enable','off');
        set(ch2skale,'enable','off');
    else 
        set(varza,'enable','on');
        set(gedita,'enable','on');
        set(IK,'enable','on');
        set(UK,'enable','on');
        set(ch2skale,'enable','on');
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55
 function keistifiltra(~,~)
     %ijungti reikalinga filtro juosta
     b=iu.range;
     switch b
         case 'HF'
             a=find(filad==get(filsad,'SelectedObject'));
             iu.filter=a;
             set(filszd,'SelectedObject',filzd(a));%kad teisingai rodytu
         case 'LF'
             a=find(filzd==get(filszd,'SelectedObject'));
             iu.filter=a;
             set(filsad,'SelectedObject',filad(a));%kad teisingai rodytu
     end
 end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function kalmat(mode,~)
    switch mode
        case 'Callibr.'
            set(kals,'SelectedObject',kal(1)); % 2-matavimas, 1 kalibravimas
        case 'Meas.'
            set(kals,'SelectedObject',kal(2)); %     
    end
    %ijungti kalibravima/matavima
    a=find(kal==get(kals,'SelectedObject'));
    if a==2
        iu.mode='MEAS';
    else
        iu.mode='CAL';
    end
    if ~get(kalmattrauto,'value');
        set(ch2au,'value',0);ch2auto;
        set(I_auto,'value',0);set_I_auto;return
    end
    if a==1 %jei jungiamas kalibravimas, nustatoma gen itampa
        nominali_itampa=get(gedita,'string'); %isimename gen itampa.ja reiks nustatyti pereinant i matavimo veika
        b='a=#get(Ustip,''value'')';
        c=zinute_dif(b); %surandame dif. stiprintuvo stiprinima
        d='a=#get(ch2skale,''value'')';
        e=zinute_dif(d)-1; %surandame oscdif Ch2 skale
        itampa_del_zondu=2^(e-(2*(c-1)))*.1;%randam didziausia galima gen itampa kalibruojant dif
        set(ch2au,'value',0);ch2auto;
        set(I_auto,'value',0);set_I_auto;
        if (strcmp(iu.attenuator,'OFF')&&(iu.gain==1.7))||(strcmp(iu.attenuator,'ON')&&(iu.gain==6.8))
            %jei atteniuatoriaus ir stiprintuvo perdavimas 1 ir1, arba 1/4 ir 4
            am=min(scp.Channels.Range)/2;
        elseif strcmp(iu.attenuator,'ON')&&(iu.gain==1.7)    
            %jei ateniuatorius 1/4, o sroves st 1
            am=min(4*scp.Channels(1).Range,scp.Channels(2).Range)/2;
            if am>2; am=2;end
        elseif strcmp(iu.attenuator,'OFF')&&(iu.gain==6.8)        
            %jei ateniuatorius 1, o sroves st 4
            am=min(scp.Channels(1).Range/4,scp.Channels(2).Range)/2;
        end
        am=min(am, itampa_del_zondu);   
        set(gedita,'string',num2str(am));
        gsignalvolt;
    else %jei matavimas
        set(gedita,'string',nominali_itampa);
        gsignalvolt;
        set(ch2au,'value',1);ch2auto;
        set(I_auto,'value',1);set_I_auto;
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function stipu(~,~)
    %ijungti/isjungti U atenuatoriu
    a=find(UK==get(Ustip,'SelectedObject'));
    if a==1
        iu.attenuator='ON';
    else
        iu.attenuator='OFF';
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function stipi(~,~)
    %ijungti/isjungti I stiprintuva
    a=find(IK==get(Istip,'SelectedObject'));
    if a==2
        iu.gain=1.7;
    else
        iu.gain=6.8;
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%OSC funkcijos%%%%%%%%%%%%%%%%%%%%%%%%
function measrate(mode,~) 
    switch mode
            case 'Fast'
                set(rate,'value',1);
            case 'Normal'
                set(rate,'value',2);
            case 'Slow'
                set(rate,'value',3);
    end
    oscauto;
end
function oscauto(~,~)
    %automatiskai parinkti rezoliucija, diskretizavimo dazni ir sampliu kieki
    %f=str2double(get(geditf,'string'));
    f=ge.Frequency;
    a=get(fnrcont,'value');
    if a==1
        set(resol,'enable','off');
        set(editsf,'enable','off');
        set(editns,'enable','off');
        set(rate,'enable','on');
        rezf=find([0 1560000 25000000]<f,1,'last');%automatine rezoliucija
        aa=get(resol,'value');
        if aa~=rezf
            set(resol,'value',rezf);
            res;
        end
%         samf=find([0 1 6 40 250 1500 7500 97500 1560000]<f,1,'last');%automatinis diskretizavimo daznio parinkimas
%         samff=[50.0032 500.8013 3004.8077 3004.8077 3004.8077 2*16276.0417 195312.5 3125000 25000000];
        samf=find([0 .1 1 10 250 1560000]<=f,1,'last');%automatinis diskretizavimo daznio parinkimas
        samff=[31250 31250 312500 312500 3125000 50000000];
        aa=str2double(get(editsf, 'string')); 
        if aa~=samff(samf);
            b=num2str(samff(samf));
            set(editsf, 'string', b);
            sf;
        end
%         nnnsam=samff(samf)*6/f;%%????????
%         nsam=find([0 1 6 20 230 1500 7500 97500 1560000]<f,1,'last');% automatinis sampliu kiekis
        daugiklis=get(rate,'value');
        periodu=daugiklis*[5 5 5 fix(2e5/samff(samf)*f) fix(1.3e5/samff(samf)*f) fix(5e5/samff(samf)*f)];
        bursts=periodu(samf);
        %nnsam=round(daugiklis*[5/f*samff(samf) 5/f*samff(samf) 5/f*samff(samf) 2e5 1.5e5 5e5]);
        nnsam=fix(bursts*samff(samf)/f);
        aa=str2double(get(editns, 'string')); 
        if aa~=nnsam;%(samf);
            %b=num2str(nnsam(samf));
            b=num2str(nnsam);
            set(editns, 'string', b);
            ns;
        end
        %nustatome gen periodus
        %bursts
        ge.BurstCount=bursts;
    else
        set(resol,'enable','on');
        set(editsf,'enable','on');
        set(editns,'enable','on');
        set(rate,'enable','off');
    end
     
end
function ch1sk(~,~)  
    %ijungti 1 kanalo skale 
    a=get(ch1skale,'value');
    b=get(ch1skale,'string');
    c=b{a};c=c(1:3);c=str2double(c);
    scp.Channels(1).Range=c;
end
function ch1acdc(~,~)
    %ijungti 1 kanalo ac/dc
    scp.Channels(1).Coupling=get(ch1jung,'value');    
end
function ch2sk(~,~)
     %ijungti 2 kanalo skale 
    a=get(ch2skale,'value');
    b=get(ch2skale,'string');
    c=b{a};c=c(1:3);c=str2double(c);
    scp.Channels(2).Range=c;
end
function ch2acdc(~,~)
    %ijungti 2 kanalo ac/dc
    scp.Channels(2).Coupling=get(ch2jung,'value');    
end
function res(~,~)
    %ijungti reikiama rezoliucija
    a=get(resol,'value');
    b=get(resol,'string');
    c=b{a};c=c(1:2);c=str2double(c);
    scp.Resolution=c;
    fs=scp.SampleFrequency;
    b=num2str(fs);
    set(editsf, 'string', b);
end
function sf(~,~)
    %ijungti reikiama diskratizavimo f
    a=get(editsf, 'string');
    b=str2double(a);
    scp.SampleFrequency=b;
    fs=scp.SampleFrequency;
    b=num2str(fs);
    set(editsf, 'string', b);      
end
function ns(~,~)
    %ijungti reikiama tasku skaiciu
    a=get(editns, 'string');
    b=str2double(a);
    scp.RecordLength=b;
end
function rez=komanda_iu(kom)%priimmama komanda is isores
    set(editkom,'string',kom);
    kk=find(kom=='#', 1); %kai reikia rezultato kreipiamasi zinute_iu('rez= komanda')-su tarpu
    if isempty(kk)
        eval(kom);
    else
        a=kom(kk+1:length(kom));
        rez=eval(a);   
    end
end
function comand(~,~)
    %pasiusti norima komanda
    %komandos formatas:scp.X.Y=Z (kai savyb4 keiciama)
    %scp.X.Y- kai norima paziureti savybes busena.
    a= get(editkom,'string');
    kk=find(a=='=', 1);
    if ~isempty(kk)
        eval(a);
    else
        b=eval(a);
        set(editkom,'string',b);
    end
    %Toliau nuskaitome rodomasias osc savybe- gal but jos pasikeite
    set(editns, 'string',num2str(scp.RecordLength));
    set(editsf, 'string', num2str(scp.SampleFrequency));
    kk=find(scp.Resolution==scp.Resolutions);
    set(resol, 'string', kk);
    kk=find(scp.Channels(1).Coupling==scp.Channels(1).Couplings);
    set(ch1jung,'value',kk);
    kk=find(scp.Channels(2).Coupling==scp.Channels(2).Couplings);
    set(ch2jung,'value',kk);
    kk=find(scp.Channels(1).Range==scp.Channels(1).Ranges);
    set(ch1skale,'value', kk);
    kk=find(scp.Channels(2).Range==scp.Channels(2).Ranges);
    set(ch2skale,'value', kk);
    
end
function trigger(~,~)
    a=get(trig,'value');
    scp.Channels(1).TriggerEnabled=0;
    scp.Channels(2).TriggerEnabled=0;
    for iijj=1:6
        scp.TriggerInputs(iijj).Enabled=0;
    end       

    if a==1
        scp.Channels(1).TriggerEnabled=1;
    elseif a==2
        scp.Channels(2).TriggerEnabled=1;  
    elseif a==3
        scp.TriggerInputs(1).Enabled=1;
    elseif a==4
        scp.TriggerInputs(2).Enabled=1;
    elseif a==5
        scp.TriggerInputs(3).Enabled=1;
    elseif a==6
        scp.TriggerInputs(4).Enabled=1;
    elseif a==7
        scp.TriggerInputs(5).Enabled=1;
    elseif a==8
        scp.TriggerInputs(6).Enabled=1;
    end
end
%%%%%%%%%%%%%%%%%%%%%%Gen funkcijos%%%%%%%%%%%%%%%%%%%%%%%%%%%
function gsym(~,~)
    %gen. simetrijos nustatymas
    am=str2double(get(groutedit,'string'));
    if (am>=1)||(am<=0)
        beep;disp('Symmetry!!!');
        am=ge.Symmetry;
        set(groutedit,'string',num2str(am));
        return;
    end
    ge.Symmetry=am;      
end
 function ch2auto(~,~) %sios funkcijos pagalba
     % CH1 surisamas su generatoriaus isejimo itampa, CH1 skale parenkama
     % automatiskai, keiciant gen itampa
     if ~get(ch2au,'value')
         %sujungti_CH4_skales('Callibr.');
         set(ch2skale,'enable','on');return
     end
     set(ch2skale,'enable','off');
     umaks=(ge.Amplitude+ge.Offset)/daliklis;
     %umaks=str2double(get(gedita, 'string'))+abs(str2double(get(geditdc, 'string'))); 
     kk=find(umaks./scp.Channels(2).Ranges<=0.85,1);
     kkk=get(ch2skale,'value');
     if kk==kkk
         return;
     end
     if ~isempty(kk)
        set(ch2skale,'value',kk);ch2sk;
     else set(ch2skale,'value',9);ch2sk;
        beep;disp('Error!!!');   
     end
 end
function goutput(~,~)
    %gen. isejimas in/is
    a=get(gpoponoff,'value');
    ge.OutputOn=a-1;
end
function gsignalform(~,~)
    a=get(gpopform,'value');
    ge.SignalType=ge.SignalTypes(a);
end
function gsignalvolt(~,~)
    am=get(gedita, 'string');
    ge.Amplitude=daliklis*str2double(am);
    ch2auto;%pakeiciama sakle, jei reikia
    zinute_dif('ranges_aut');%valdome TiePieHS4 Ch1,Ch3,Ch4 skales automatiskai
end
function gsignalfreq(~,~)
    am=get(geditf, 'string');
    ge.Frequency=str2double(am);
    oscauto;%nustatomi samplai, resolution ir diskr. daznis
    zinute_dif('oscauto');%valdome TiePieHS4 ato parametrai
    fcontrol;%nustatomas filtras
    keistivarza;
end
function gsignaldc(~,~)
    am=get(geditdc, 'string');
    ge.Offset=str2double(am)*daliklis;
    ch2auto;%pakeiciama sakle, jei reikia
end 
%%%%%%%%%%%%%%%%% GRAFIKA %%%%%%%%%%%%%%%%%%%%%%%
function matytigraf1
    matyti(1)=get(kanalas1,'value');
    matyti(2)=get(kanalas2,'value');
    if matyti(1)&&matyti(2);
        return
    else matytigraf
    end
end
function matytigraf(~,~)
    matyti(1)=get(kanalas1,'value');
    matyti(2)=get(kanalas2,'value');
    if matyti(1)
        set(hspek(1),'visible','on');
        set(hform(1),'visible','on');
    else 
        set(hspek(1),'visible','off');
        set(hform(1),'visible','off');
    end
    if matyti(2)
        set(hspek(2),'visible','on');
        set(hform(2),'visible','on');
    else 
        set(hspek(2),'visible','off');
        set(hform(2),'visible','off');
    end
end
function Rezultatas=pirm(mode,~)
    %priimti duomenis is Osc ir piesti oscilograma ir spektrograma
    if mode~=true;mode=false;end
    cont=false;
    while ~cont;
        tvarka=false;
        while (~tvarka);
            if ~mode; scp.Start;ge.Start;end
            if get(intext,'value')==1%jei valdymas is grafines paneles, uzgesiname.
                for iij=1:length(valdkintamieji)
                  set(valdkintamieji{iij},'enable','off');
                end
            end
            fgen=ge.Frequency; 
            fs=scp.SampleFrequency;
            %ge.Start;
            ntasku= scp.RecordLength;   
            t(1:ntasku)=1/fs:1/fs:ntasku/fs;
            kak=fix(ntasku*fgen/fs);
            nftasku=fix(fs/fgen*kak);
            nftasku=ntasku;%jau padaryta
            langas=hanning(nftasku);
            svfak=sum(langas);
            f=0:fs/nftasku:fs/2-fs/nftasku;
            fftmin=abs(fgen-f);
            an=find(fftmin==min(fftmin));
            set(sub1_axes,'Ylim',[-max(scp.Channels.Range) max(scp.Channels.Range)]);
            set(sub1_axes,'Xlim',[0 5/fgen]);
            Busenos=bandu('nieko');%formuojame galimu busenu registra, nes turime laiko
            while ~( scp.IsDataReady || scp.IsRemoved )
                pause( 10e-3 ) % 10 ms delay, to save CPU time.
            end
            if scp.IsRemoved
                clear Scp;
                error( 'TiePie HS5 gone!' )
            end
            duom = scp.GetData';
            duom(1,:)=-duom(1,:);
            if get(I_auto,'value')
                 tvarkyti(duom,Busenos);
            else
                 tvarka=true;
            end
            if ~mode;ge.Stop;end
            if and(mode,~tvarka)
                Rezultatas='netvarka';return
            end
        end
        if nepiesti;
            return
        end
        duomm(1,:) = duom(1,1:nftasku).*langas';
        duomm(2,:) = duom(2,1:nftasku).*langas';         
        b1=fft(duomm(1,:));
        b2=fft(duomm(2,:));
%         plot(abs(b2));
        bbb=[an-1 an an+1];
        bb1=2*abs(b1(bbb))/svfak;
        bb2=2*abs(b2(bbb))/svfak;
        cnn=b2(bbb)./b1(bbb);
        Rezultatas=.25*(cnn(1)+cnn(3))+.5*cnn(2);
        fi=angle(Rezultatas)*180/pi;
        m=abs(Rezultatas);
        Noisandsig=2*abs(b1(1:fix(nftasku/2)))/svfak;
        spektras1=20*log10(Noisandsig);
        spektras2=20*log10(abs(b2(1:fix(nftasku/2)))/svfak)+6;    
    %     figure(1)
    %     caca=1:bbb(1);
    %     plot(caca,20*log10(abs(Nois(1:bbb(1))).^2))
        Nois=sqrt(sum(Noisandsig(3:bbb(1)-1).^2)*fs/ntasku/fgen);%randame triuksma dc ir signala ismetame
        lenspe=length(spektras1);
        if ~isnumeric(hspek)
            delete(hspek);delete(hform);
        end
        hspek=plot(sub2_axes,f,spektras1(1:lenspe),'b',f,spektras2(1:lenspe),'c');
        hform=plot(sub1_axes,t,duom(1,:),'b',t,duom(2,:),'c');
        set(tx1,'string',['U1=' num2str(bb1(2),'%0.5g') ' V']);
        set(tx2,'string',['U2=' num2str(bb2(2),'%0.5g') ' V']);
        set(txm,'string',['M=' num2str(m,'%0.5g')]);
        set(txfi,'string',['FI=' num2str(fi,'%0.5g')]);
        set(N,'string',['N=' num2str(Nois,'%0.5g') ' V']);
        set(SN,'string',['S/N=' num2str(20*log10(bb1(2)/Nois/2),'%0.5g') 'dB']);
        matytigraf1;
        if get(continuous,'value')
            pause(.1);cont=false;tvarka=false;
        else
            cont=true;
        end
        
    end
   % Rezultatas=m*exp(1j*pi*fi/180);%admitansas
    if strcmp(iu.attenuator,'OFF');
         att=1;
     else
         att=0.25;
    end
    Rezultatas=Rezultatas(1)*att*iu.gain/1.7;
    if get(intext,'value')==1
        for iij=1:length(valdkintamieji)
            set(valdkintamieji{iij},'enable','on');
        end
    end
end
%%%%%%%%%%%%%%%%%%%%KITOS FUNKCIJOS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 function tvarkyti(duom,Busenos) %busenos sroves signalo matavimui sutvarkymas
     if strcmp(iu.attenuator,'OFF')
         att=1;
     else
         att=0.25;
     end
     busena=[ge.Amplitude/daliklis att iu.gain iu.resistor scp.Channels(1).Range];
     maxch2=max(abs(duom(1,:)));
     kkk=find(busena(1)==[.4 .1 .025 6.25e-3],1); 
     if isempty(kkk)
         beep; set(gedita,'string',num2str(Busenos.Genvoltage(29)));gsignalvolt;%nustatome gen itampa, jei neteisinga
         set(Istip,'SelectedObject',IK(2)); stipi;
         set(Ustip,'SelectedObject',UK(2)); stipu;
         pause(.02);return;
     end 
     kk=find(Rmat(3,:)-ge.Frequency>=0,1,'last');
     kkk=length(Busenos.ResistorNo);
     if kkk==33;
         Busenos.ResistorNo(30:33)=kk;
     end
     if kkk==31;
         Busenos.ResistorNo(30:31)=kk;
     end
     kkk=find(Busenos.ResistorNo>kk);
     if ~isempty(kkk)
         Busenos.Genvoltage(kkk)=[];
         Busenos.AttenuatorU(kkk)=[];
         Busenos.GainI(kkk)=[];
         Busenos.ResistorNo(kkk)=[];
         Busenos.Ch2scale(kkk)=[];
     end
     dabar=log2(maxch2/scp.Channels(1).Range);
     delta=0;
     if dabar>-.23;
         delta=-1;
     end
     if dabar<-1.62;
         delta=-round(dabar+1.12);%randam per kiek pastumti busenos registra (nuo atskaitos)
     end
     ind=log2( Busenos.Genvoltage(:)/.1)+log2(Busenos.AttenuatorU(:))+log2(Busenos.GainI(:)/1.7)+2*Busenos.ResistorNo(:)-log2(Busenos.Ch2scale(:)/.2);
     % visi galimi indeksai
     yra=log2(busena(1)/.1)+log2(busena(2))+log2(busena(3)/1.7)+2*busena(4)-log2(busena(5)/.2); %dabartinis indeksas
     ind=ind-yra;
     bbb=find(ind==min(abs(ind)));%randame artimiausia indeksa
     gerabusena=[Busenos.Genvoltage(bbb) Busenos.AttenuatorU(bbb) Busenos.GainI(bbb) Busenos.ResistorNo(bbb) Busenos.Ch2scale(bbb)];
     if sum(busena-gerabusena)~=0 %jei ijungta nesamoninga busena
         reikia=12;
     else
         reikia=bbb+delta;
     end
     if reikia>length(Busenos.GainI);
         reikia=length(Busenos.GainI);
     end
     if reikia<1
         reikia=1;
         beep; disp('impedance of the sample is too smaal'); 
     end 
     tvarka=true;
     
     if busena(1)~= Busenos.Genvoltage(reikia)
         set(gedita,'string',num2str(Busenos.Genvoltage(reikia)));gsignalvolt;tvarka=false;%nustatome gen itampa, jei neteisinga
     end
     if busena(3)~=Busenos.GainI(reikia)
         if Busenos.GainI(reikia)==6.8
             set(Istip,'SelectedObject',IK(1));
         else
             set(Istip,'SelectedObject',IK(2));
         end
         stipi;tvarka=false;
     end
     if busena(2)~=Busenos.AttenuatorU(reikia)
         if Busenos.AttenuatorU(reikia)==1
             set(Ustip,'SelectedObject',UK(2));
         else
             set(Ustip,'SelectedObject',UK(1));
         end
         stipu;tvarka=false;
     end
     if busena(4)~=Busenos.ResistorNo(reikia)
         set(varzas,'SelectedObject',varza(Busenos.ResistorNo(reikia))); keistivarza;tvarka=false;
     end
     if busena(5)~=Busenos.Ch2scale(reikia)
         kkk=find([.2 .4 .8 2]==Busenos.Ch2scale(reikia));
         set(ch1skale,'Value',kkk); ch1sk;tvarka=false;
     end
     if tvarka==false;
         pause(.02);
     end
 end
 function vald(mode,~)
     switch mode
         case 'GUI'
             set(intext,'value',1); % 
         case 'Appl.'
                set(intext,'value',2); %     
     end
     if get(intext,'value')==2
          for iij=1:length(valdkintamieji)
             set(valdkintamieji{iij},'enable','off');
          end
          a=find(kal==get(kals,'SelectedObject'));
          set(fnrcont,'value',1);oscauto;
          set(fcont,'value',1);fcontrol;
          set(kalmattrauto,'value',1);
          if a==2
             kalmat('nieko');
          end
     else
         for iij=1:length(valdkintamieji)
             set(valdkintamieji{iij},'enable','on');
         end
         set(I_auto,'value',0);
         set(kalmattrauto,'value',0);
         set(fcont,'value',0);
         set(fnrcont,'value',0);
         set(ch2au,'value',0);
     end
  end
function Busenos=bandu(mode,~)% cia nustatomos galimos busenos, priklauspmai nuo max leidziamos bandinio itampos
    switch mode
        case '0.4 V'
            set(maxu,'value',1); % 2-matavimas, 1 kalibravimas
        case '0.1 V'
            set(maxu,'value',2); % 
        case '25 mV'
            set(maxu,'value',3); %
    end
    clear Busenos;
    aa=get( maxu,'value');
    Busenos=struct('Genvoltage',1,'AttenuatorU',.25,'GainI',1,'ResistorNo',3,'Ch2scale',.2);
    load('Busenos.mat');
    switch aa
        case 2
            return
        case 3
            Busenos.AttenuatorU(1:29)=.25; Busenos.GainI(1:29)=6.8; Busenos.Genvoltage(30:31)=[];Busenos.AttenuatorU(30:31)=[];
            Busenos.GainI(30:31)=[];Busenos.ResistorNo(30:31)=[];Busenos.Ch2scale(30:31)=[];
        case 1
            Busenos.Genvoltage(32:33)=4; Busenos.AttenuatorU(32:33)=1; Busenos.GainI(32:33)=6.8;
            Busenos.ResistorNo(32:33)=11; Busenos.Ch2scale(32:33)=[.4 .2];
    end
end

function my_closereqIU(selection,~)
    if strcmp(selection,'shutdown')
        selection='Yes';
    end
    if  ~strcmp(selection,'Yes')
        selection = questdlg('Ar tikrai norite uzdaryti langa?',...
                     'Uzdryti IU valdymo langa',...
                     'Yes','No','Yes');
    end
    switch selection
        case 'Yes'
            %delete(gcf);
            delete(figure(20));
            %clear all;
        case 'No';return
    end
end
function help
    disp ''
    disp 'zinute_iu('Komanda') priimti komandai (string formate) is isores.'
    disp 'Vykdoma bet kuri iu driverio paprograma arba komanda.'
    disp 'Kai reikia rezultato kreipiamasi 'zinute_iu('rez=#komanda')' t.y.su #'
end
end
